jobs:
 build:
   machine: true
   environment: &environment_variables
     DOCKER_REPO: chre2628/helloworld
     DOCKER_CACHE_FROM: latest
   steps:
      - type: checkout
      - type: shell
        name: "Determine which Projects need to be built"
        command: |
          COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
          echo "Commit range: " $COMMIT_RANGE
          git diff $COMMIT_RANGE --name-status
          if [[ $(git diff $COMMIT_RANGE --name-status | grep "HelloWorld") != "" ]]; then
            echo "setting build circleci lambda"
            touch /tmp/build-circleci.lambda
            git diff $COMMIT_RANGE --name-status >> /tmp/build-circleci.lambda
          fi
          if [[ $(git diff $COMMIT_RANGE --name-status | grep "lambda/terminate_expired_servers") != "" ]]; then
            echo "setting build terminate-expired-servers lambda"
            touch /tmp/build-terminate-expired-servers.lambda
          fi
      - type: shell
        name: "HelloWorld Build"
        command: |
          if [ -f "/tmp/build-circleci.lambda" ]; then
           echo "[EXECUTING] HelloWorld Build"
           cat /tmp/buil-circleci.lambda
          else 
           echo "[SKIPPING] HelloWorld Build"
          fi 
      - type: shell
        name: "Remove temporary files"
        command: |
          rm -f /tmp/build-*

