jobs:
 build:
   machine: true
   environment: &environment_variables
     DOCKER_REPO: chre2628/helloworld
     DOCKER_CACHE_FROM: latest
     PROJECTS_TO_BUILD: /tmp/projects.to.build
   steps:
      - type: checkout
      - type: shell
        name: "Determine which Projects need to be built"
        command: |
          COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
          echo "Commit range: " $COMMIT_RANGE
          git diff $COMMIT_RANGE --name-status | grep "/" | cut -f2 | awk -F'/' '{print $1}' > ${PROJECTS_TO_BUILD}
          if [[ $(wc -l ${PROJECTS_TO_BUILD} | awk '{print $1}') == 0 ]]; then
           echo "No projects to build."
          else
           echo "Project(s) to build:"
           cat ${PROJECTS_TO_BUILD} | while read project;
           do
            echo " - ${project}"
           done
          fi
      - type: shell
        name: "Build Projects"
        command: |
          if [[ $(wc -l ${PROJECTS_TO_BUILD} | awk '{print $1}') > 0 ]]; then
           cat ${PROJECTS_TO_BUILD} | while read project;
           do 
            echo "Building ${project}..."
            echo "Build execution complete.\n"
           done
          else 
           echo "There are no projects to build."
          fi 
      - type: shell
        name: "Remove temporary files"
        command: |
          rm -f /tmp/build-*

